ALTER TABLE orders
    ALTER COLUMN total_price TYPE DOUBLE PRECISION,
    ALTER COLUMN total_price SET DEFAULT NULL;

ALTER TABLE order_item
    ALTER COLUMN quantity TYPE INTEGER,
    ALTER COLUMN price TYPE DOUBLE PRECISION;

DROP TABLE orders_items;